on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_blueprint:
    runs-on: ubuntu-latest
    name: Build blueprint
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain $(cat lean-toolchain)

      - name: Build project
        run: make build

      ## don't do this yet until mathlib dependencies are worked out
      #- name: Cache mathlib docs
      #  uses: actions/cache@v3
      #  with:
      #    path: |
      #      .lake/build/doc/Init
      #      .lake/build/doc/Lake
      #      .lake/build/doc/Lean
      #      .lake/build/doc/Std
      #      .lake/build/doc/Mathlib
      #      .lake/build/doc/declarations
      #    key: MathlibDoc-${{ hashFiles('lake-manifest.json') }}
      #    restore-keys: |
      #      MathlibDoc-

      - name: Build documentation
        run: make doc

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # cache pip dependencies

      - name: Install blueprint apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libgraphviz-dev pdf2svg dvisvgm texlive-full

      - name: Install blueprint dependencies
        run: |
          cd blueprint && pip install -r requirements.txt

      - name: Build blueprint and copy to `docs/blueprint`
        run: |
          make blueprint

      - name: Copy documentation to `docs/docs`
        run: |
          cp -r .lake/build/doc docs/docs

      - name: Bundle dependencies
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Bundle website
        working-directory: docs
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload docs & blueprint artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
